### ISSUE TITLE
aws cli Header length error when using SelectObjectContent 

### ISSUE THREAD

**Issue by benmcclelland** [versity/versitygw#286]
**Describe the bug**
If we add the SelectObjectContent implementation to the posix backend, the aws cli gets the following error:
```
Header length of 1701016655 exceeded the maximum of 131072
```
 
**To Reproduce**
Add the following to the posix backend:
```
func (p *Posix) SelectObjectContent(context.Context, *s3.SelectObjectContentInput) (s3response.SelectObjectContentResult, error) {
	return s3response.SelectObjectContentResult{}, nil
}
```

Add "bucket" bucket to the system.
```
aws --endpoint-url http://127.0.0.1:7070  s3 mb s3://bucket
```

And run this cli command against the gateway:
```
aws --endpoint-url http://127.0.0.1:7070 s3api select-object-content --bucket bucket --key aaa.parquet --expression "SELECT * FROM s3object" --expression-type "SQL" --input-serialization="CSV={FileHeaderInfo=string,Comments=string,QuoteEscapeCharacter=string,RecordDelimiter=string,FieldDelimiter=string,QuoteCharacter=string,AllowQuotedRecordDelimiter=true},CompressionType=string,JSON={Type=string},Parquet={}" --output-serialization="CSV={QuoteFields=string,QuoteEscapeCharacter=string,RecordDelimiter=string,FieldDelimiter=string,QuoteCharacter=string},JSON={RecordDelimiter=string}" /dev/stdout
```

Then we get the following error:
```
Header length of 1701016655 exceeded the maximum of 131072
```

**Expected behavior**
Expect empty results since the posix implementation returns `s3response.SelectObjectContentResult{}`

**Comment by benmcclelland** [comment]
more client side debug

```
2023-10-12 08:42:30,830 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:7070
2023-10-12 08:42:30,831 - MainThread - urllib3.connectionpool - DEBUG - http://127.0.0.1:7070 "POST /bucket/aaa.parquet?select&select-type=2 HTTP/1.1" 200 153
2023-10-12 08:42:30,831 - MainThread - botocore.parsers - DEBUG - Response headers: {'Server': 'VERSITYGW', 'Date': 'Thu, 12 Oct 2023 15:42:30 GMT', 'Content-Type': 'application/xml', 'Content-Length': '153'}
2023-10-12 08:42:30,831 - MainThread - botocore.parsers - DEBUG - Response body:
<urllib3.response.HTTPResponse object at 0x110769270>
2023-10-12 08:42:30,831 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.SelectObjectContent: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x1107b8190>>
2023-10-12 08:42:30,831 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2023-10-12 08:42:30,831 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.SelectObjectContent: calling handler <bound method S3RegionRedirectorv2.redirect_from_error of <botocore.utils.S3RegionRedirectorv2 object at 0x1107b7450>>
2023-10-12 08:42:30,832 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.SelectObjectContent: calling handler <bound method S3SelectStreamOutputArgument.save_file of <awscli.customizations.s3events.S3SelectStreamOutputArgument object at 0x11024e990>>
2023-10-12 08:42:30,832 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 460, in main
  File "awscli/clidriver.py", line 595, in __call__
  File "awscli/clidriver.py", line 798, in __call__
  File "awscli/clidriver.py", line 929, in invoke
  File "awscli/clidriver.py", line 941, in _make_client_call
  File "awscli/botocore/client.py", line 341, in _api_call
  File "awscli/botocore/client.py", line 686, in _make_api_call
  File "awscli/botocore/hooks.py", line 228, in emit
  File "awscli/botocore/hooks.py", line 211, in _emit
  File "awscli/customizations/s3events.py", line 86, in save_file
  File "awscli/botocore/eventstream.py", line 585, in __iter__
  File "awscli/botocore/eventstream.py", line 594, in _create_raw_event_generator
  File "awscli/botocore/eventstream.py", line 528, in __next__
  File "awscli/botocore/eventstream.py", line 520, in next
  File "awscli/botocore/eventstream.py", line 466, in _parse_prelude
  File "awscli/botocore/eventstream.py", line 457, in _validate_prelude
```

**Comment by benmcclelland** [comment]
The response body contains more structure than we are currently encoding.  The AWS docs are here: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTSelectObjectAppendix.html
