### ISSUE TITLE
After ACLs have been disabled by default, the s3cmd info command via versitygw throws exception

### ISSUE THREAD

**Issue by lrm25** [versity/versitygw#664]
**Describe the bug**
An exception is thrown when the `s3cmd info` command is called.  Initially I thought this was due to the ACL change, and thought that the ability to re-enable ACLs would fix it.  However, the error continues to be thrown even with ACLs enabled, and the error does not occur when going direct to S3, whether or not the ACLs are enabled.

The error looks like this:

```
s3://versity-gwtest-bucket-one/ (bucket):
      Location:  us-east-1
      Payer:     none
      Ownership: BucketOwnerPreferred
      Versioning:none
      Expiration rule: none
      Block Public Access: none
      Policy:    none
      CORS:      <?xml version="1.0" encoding="UTF-8"?>
   <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Delimiter></Delimiter><EncodingType></EncodingType><IsTruncated>false</IsTruncated><Marker></Marker><MaxKeys>1000</MaxKeys><Name>versity-gwtest-bucket-one</Name><NextMarker></NextMarker><Prefix></Prefix><RequestCharged></RequestCharged><ResultMetadata></ResultMetadata></ListBucketResult>

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
       An unexpected error has occurred.
     Please try reproducing the error using
     the latest s3cmd code from the git master
     branch found at:
       https://github.com/s3tools/s3cmd
     and have a look at the known issues list:
       https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
     If the error persists, please report the
     following lines (removing any private
     info as necessary) to:
      s3tools-bugs@lists.sourceforge.net
   
   
   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   
   Invoked as: /opt/homebrew/bin/s3cmd --no-check-certificate info s3://versity-gwtest-bucket-one
   Problem: <class 'KeyError: '{http://www.w3.org/2001/XMLSchema-instance}type'
   S3cmd:   2.4.0
   python:   3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
   environment LANG=NOTSET
   
   Traceback (most recent call last):
     File "/opt/homebrew/bin/s3cmd", line 3627, in <module>
       rc = main()
            ^^^^^^
     File "/opt/homebrew/bin/s3cmd", line 3524, in main
       rc = cmd_func(args)
            ^^^^^^^^^^^^^^
     File "/opt/homebrew/bin/s3cmd", line 1141, in cmd_info
       acl = s3.get_acl(uri)
             ^^^^^^^^^^^^^^^
     File "/opt/homebrew/lib/python3.12/site-packages/S3/S3.py", line 1141, in get_acl
       acl = ACL(response['data'])
             ^^^^^^^^^^^^^^^^^^^^^
     File "/opt/homebrew/lib/python3.12/site-packages/S3/ACL.py", line 97, in __init__
       self.parseGrants(tree)
     File "/opt/homebrew/lib/python3.12/site-packages/S3/ACL.py", line 107, in parseGrants
       grantee.xsi_type = g.attrib['{http://www.w3.org/2001/XMLSchema-instance}type']
                          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   KeyError: '{http://www.w3.org/2001/XMLSchema-instance}type'

```

**To Reproduce**
1.  Create a bucket via versitygw.
2.  Run the info command, e.g. `s3cmd <params> --no-check-certificate info "s3://<bucket name>"`

**Expected behavior**
Similar to direct, something like the following, without an error:

```
s3://versity-gwtest-bucket-luke-three/ (bucket):
      Location:  us-east-1
      Payer:     BucketOwner
      Ownership: BucketOwnerEnforced
      Versioning:none
      Expiration rule: none
      Block Public Access: BlockPublicAcls,IgnorePublicAcls,BlockPublicPolicy,RestrictPublicBuckets
      Policy:    none
      CORS:      none
      ACL:       <user ID>: FULL_CONTROL
```

**Server Version**
 output of
```
Version  : v1.0.2
Build    : 19f8b19
BuildTime: 2024-07-08_03:38:03PM
Darwin Lukes-MacBook-Pro.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:25 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6030 arm64
```

**Comment by benmcclelland** [comment]
update from investigation:
 GetBucketAcl action fails, because the Type  in ACL schema is required. s3cmd  expects Type  to be set, that's why getting the bucket acl fails. On the other hand our gateway doesn't use this property. You can check the schema below:
```
<AccessControlPolicy>
   <Owner>
      <DisplayName>string</DisplayName>
      <ID>string</ID>
   </Owner>
   <AccessControlList>
      <Grant>
         <Grantee>
            <DisplayName>string</DisplayName>
            <EmailAddress>string</EmailAddress>
            <ID>string</ID>
            <xsi:type>string</xsi:type>
            <URI>string</URI>
         </Grantee>
         <Permission>string</Permission>
      </Grant>
   </AccessControlList>
</AccessControlPolicy>
```
xsi:type  here is an enum with the following values:
CanonicalUser
AmazonCustomerByEmail
Group

We will likely just go ahead an populate type: CanonicalUser to make s3cmd happy in the case
