### ISSUE TITLE
[Bug] - Unable to backup files to versity posix with QNAP HBS3 Hybrid Backup Sync

### ISSUE THREAD

**Issue by derreisende77** [versity/versitygw#738]
**Describe the bug**
I am trying to backup a QNAP NAS with vendor provided HBS3 to a posix versity server. In this specific case an iTunes folder needs to be transferred.
Backup starts and then fails with various "Key Errors" like the following example:
```
App Name: Hybrid Backup Sync
Category: Job Status
Message: [Hybrid Backup Sync] Backup job "backup-nd": Failed to upload file/folder from "/iTunes/iTunes Media/Home Videos/Lightnings/Lightnings 2018/Lightnings 2018 3.MOV". Error: KeyError
```
Console gave the following printout:
```
20:50:57 | 200 |     709.375µs | 172.17.0.1 | POST | /qnap-nd-backup/backup-nd/iTunes/iTunes Media/Home Videos/Lightnings/Lightnings 2018/Lightnings 2018 3.MOV | - | uploads=
```
In the end the backup fails as more than 10 files could not be copied due to the above mentioned error.
All failed files were movies which were several hundred MB in size.

**To Reproduce**
You need a QNAP NAS with QTS 5.1.7 and HBS3. Then try to backup files.

**Expected behavior**
I would expect a successful backup to versity.
I have a similar backup job configured for a Minio S3 instance which works without any errors.

**Server Version**
```
docker run --pull=always --rm versity/versitygw:latest -version
latest: Pulling from versity/versitygw
Digest: sha256:03e2a4fbb7b942cad594033a7bf565b06a54573f5e82e2ef53c0636bf904dcbb
Status: Image is up to date for versity/versitygw:latest
Version  : v1.0.5
Build    : adbc8140ed85e6b5b240600b49fcd60fe2282307
BuildTime: 2024-08-06T17:53:24Z

uname -a
Linux server-HM90 6.8.0-40-generic #40-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 10:34:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by benmcclelland** [comment]
The console log is reporting successful status 200 for the create multipart upload call. Are there any other console logs with this same filename? If not, then it probably means that QNAP doesnt like something about the response that is sent back. I compared the gateway response with AWS, and the only difference is we dont have "ServerSideEncryption" part of the response.

gateway xml response:
```
{
    "Bucket": "qnap-nd-backup",
    "Key": "backup-nd/iTunes/iTunes Media/Home Videos/Lightnings/Lightnings 2018/Lightnings 2018 3.MOV",
    "UploadId": "87345531-c871-4426-a4b4-db998554354a"
}
```

AWS response:
```
{
    "ServerSideEncryption": "AES256",
    "Bucket": <bucketname>,
    "Key": "backup-nd/iTunes/iTunes Media/Home Videos/Lightnings/Lightnings 2018/Lightnings 2018 3.MOV",
    "UploadId": "rk4dp5VOHSkP.hQKZWEF6WAkspxsHTxShXEDpPWgOsnnXq.bBJaXKuX0KUMDBCL8lEjiEDVay6iObV354Y0WMnBgwYIZS_Yr7eFNOURvVoy9aWJYfjUiD2T_Bds3NocI"
}
``` 

Are there any other more detailed logs from QNAP that might have more details on the failure? I'm not sure what KeyError is, and the request is successful according to our logs, so the credentials seem good here.

**Comment by benmcclelland** [comment]
Some searching online suggests that KeyError might be HBS3 not happy with some special characters in the filenames, this doesn't really explain why it works with the other S3 endpoints though.

**Comment by derreisende77** [comment]
I had a look into HBS3 debug logs. All failed files have the same stacktrace reported:

```bash
[2024-08-16 07:08:07,306][ BakWorker][E][qnap.cloudconnector3.common.executor][executor.py:__call__:295] : Task failed
Traceback (most recent call last):
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/qnap/cloudconnector3/common/executor.py", line 284, in __call__
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/qnap/cloudconnector3/backup/replication/worker.py", line 2611, in _run
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/qnap/cloudconnector3/common/executor.py", line 275, in __call__
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/qnap/cloudconnector3/common/executor.py", line 218, in __call__
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/qnap/cloudconnector3/backup/transfer_task.py", line 198, in _run
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/qswiss/observer.py", line 49, in wrapper
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/ucc/obj2path.py", line 191, in upload
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/ucc/common.py", line 96, in outter_func
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/ucc/common.py", line 94, in outter_func
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/ucc/s3.py", line 1727, in upload_object
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/ucc/chunk_uploader.py", line 117, in upload
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/ucc/chunk_uploader.py", line 125, in _unknown_size_upload
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/ucc/chunk_uploader.py", line 173, in _unknown_size_chunked_upload
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/ucc/s3.py", line 1699, in _init
KeyError: 'InitiateMultipartUploadResult'
```

Running versity with `--debug` this is the output for the above mentioned video:

```
SDK 2024/08/16 05:08:30 DEBUG Request Signature:
---[ CANONICAL STRING  ]-----------------------------
POST
/qnap-nd-backup/backup-nd/backup-nd/iTunes/iTunes%20Media/Home%20Videos/Lightnings%EF%80%A8/Lightnings%202018/Lightnings%202018%203.MOV
uploads=
content-type:video/quicktime
host:xxx.xxxxx.xxx
user-agent:HybridBackup/24.1.0529 (QNAP; QTS 5.1.7)
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20240816T050833Z
x-amz-storage-class:STANDARD

content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-storage-class
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
---[ STRING TO SIGN ]--------------------------------
AWS4-HMAC-SHA256
20240816T050833Z
20240816/us-east-1/s3/aws4_request
399a00dabc133143d4483995f80149171ec7c3f6b49214a04e86ce691213016d
-----------------------------------------------------
2024/08/16 05:08:30 Request Body:
2024/08/16 05:08:30 Path parameters:
2024/08/16 05:08:30 bucket: qnap-nd-backup
2024/08/16 05:08:30 key: backup-nd
2024/08/16 05:08:30 *1: backup-nd/iTunes/iTunes Media/Home Videos/Lightnings/Lightnings 2018/Lightnings 2018 3.MOV
2024/08/16 05:08:30 Response Headers:
2024/08/16 05:08:30 Content-Length: 411
2024/08/16 05:08:30 Content-Type: application/xml
2024/08/16 05:08:30 Server: VERSITYGW
2024/08/16 05:08:30 Response body




05:08:30 | 200 |     740.245µs | 172.17.0.1 | POST | /qnap-nd-backup/backup-nd/backup-nd/iTunes/iTunes Media/Home Videos/Lightnings/Lightnings 2018/Lightnings 2018 3.MOV | - | uploads=
2024/08/16 05:08:38 Request headers:
2024/08/16 05:08:38 Host: xxx.xxxxx.xxx
2024/08/16 05:08:38 Content-Length: 0
2024/08/16 05:08:38 Content-Type: video/quicktime
2024/08/16 05:08:38 User-Agent: HybridBackup/24.1.0529 (QNAP; QTS 5.1.7)
2024/08/16 05:08:38 Accept-Encoding: identity
2024/08/16 05:08:38 Authorization: AWS4-HMAC-SHA256 Credential=qnap-nd-backup/20240816/us-east-1/s3/aws4_request,SignedHeaders=content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-storage-class,Signature=d4351586f2556a3de3101d5ce0b2e44f18489df1645487ceb3e5e62869d5b22f
2024/08/16 05:08:38 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2024/08/16 05:08:38 X-Amz-Date: 20240816T050841Z
2024/08/16 05:08:38 X-Amz-Storage-Class: STANDARD
2024/08/16 05:08:38 X-Forwarded-For: 256.256.256.256
2024/08/16 05:08:38 X-Forwarded-Host: xxx.xxxxx.xxx
2024/08/16 05:08:38 X-Forwarded-Proto: https
2024/08/16 05:08:38 Request query arguments:
2024/08/16 05:08:38 uploads:

SDK 2024/08/16 05:08:38 DEBUG Request Signature:
```

Note the `2024/08/16 05:08:38 Content-Length: 0` entry.

I am not familiar with this debug output but given the stacktrace from HBS3 it seems to be unhappy with an unknown size upload.

**Comment by benmcclelland** [comment]
The Content-Length is expected to be 0 for a create-multipart-upload. This is just initiating the multipart upload, and then we would expect a bunch of part uploads to follow.

This error: `KeyError: 'InitiateMultipartUploadResult'`
Looks like it thinks there is a problem with the object name in the response. There does seem to be some special characters here possibly. The object name being given to the server is:
`backup-nd/iTunes/iTunes Media/Home Videos/Lightnings/Lightnings 2018/Lightnings 2018 3.MOV`
Can you check to see if the `` is a different character in the NAS filesystem?

**Comment by benmcclelland** [comment]
I think I found the error, we are encoding the xml response as:
```
<?xml version="1.0" encoding="UTF-8"?>
<CreateMultipartUploadOutput><Bucket>qnap-nd-backup</Bucket><ChecksumAlgorithm></ChecksumAlgorithm><Key>backup-nd/backup-nd/iTunes/iTunes Media/Home Videos/Lightnings/Lightnings 2018/Lightnings 2018 3.MOV</Key><RequestCharged></RequestCharged><ServerSideEncryption></ServerSideEncryption><UploadId>b6f501b9-d5b5-4d35-b87a-7cedfc7c33b7</UploadId><ResultMetadata></ResultMetadata></CreateMultipartUploadOutput>
```
But the spec says we should be encoding the response as:
```
<?xml version="1.0" encoding="UTF-8"?>
<InitiateMultipartUploadResult>
   <Bucket>string</Bucket>
   <Key>string</Key>
   <UploadId>string</UploadId>
</InitiateMultipartUploadResult>
```

Main part being InitiateMultipartUploadResult  instead of CreateMultipartUploadOutput

We can fix the xml response for this

**Comment by derreisende77** [comment]
@benmcclelland I was unable to determine the character code for that strange symbol in the filename - my linux experience is obviously not strong enough :( 
I would be happy to test when you have fixed the response part. I really want to migrate from minio to versity for my backups.

**Comment by benmcclelland** [comment]
@derreisende77 the fix for this should be in main branch now if it was indeed this XML encoding problem.  You can test this by cloning the repo, and running `make` in the top level directory to generate the `versitygw` executable if you have a recent go compiler installed.

**Comment by benmcclelland** [comment]
I am going to open a new ticket for this. New ticket #752 created for this.
