### ISSUE TITLE
invalid timestamp format returned

### ISSUE THREAD

**Issue by benmcclelland** [versity/versitygw#752]
Backup still doesn't work, it is even worse than before. No files were transferred.
I do get the following exception in the HBS3 log:
```
[2024-08-22 10:35:33,437][ BakWorker][E][qswiss.exchook][exchook.py:exchook:31] : recording exception time data '2024-08-22T10:35:09.289776011+02:00' does not match format '%a, %d %b %Y %H:%M:%S %Z'
Traceback (most recent call last):
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/qswiss/exchook.py", line 91, in run_with_except_hook
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/qnap/cloudconnector3/backup/worker.py", line 161, in run
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/qnap/cloudconnector3/backup/replication/worker.py", line 894, in _check_job_info
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/qnap/cloudconnector3/backup/replication/worker.py", line 906, in _check_cloud_job_info_file
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/qswiss/retry_deco.py", line 40, in f_retry
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/qswiss/observer.py", line 49, in wrapper
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/ucc/obj2path.py", line 278, in listdir
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/ucc/obj2path.py", line 283, in iterdir
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/ucc/obj2path.py", line 294, in _scan
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/ucc/common.py", line 89, in outter_gen_func
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/ucc/common.py", line 86, in outter_gen_func
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/ucc/s3.py", line 1884, in list_objects
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/ucc/s3.py", line 1802, in _list_object_internal
  File "/builds/diad/sw3/hybrid-backup/hbs3-backend/qpkg/output/shared/python/lib/python3.11/site-packages/ucc/s3.py", line 1317, in __init__
  File "/share/CACHEDEV1_DATA/.qpkg/HybridBackup/CloudConnector3/python/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/CACHEDEV1_DATA/.qpkg/HybridBackup/CloudConnector3/python/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2024-08-22T10:35:09.289776011+02:00' does not match format '%a, %d %b %Y %H:%M:%S %Z'
[2024-08-22 10:35:33,525][MainThread][I][qnap.cloudconnector3.backup.backupdaemon][backupdaemon.py:run:394] : Job stopping due to process killed
[2024-08-22 10:35:33,527][MainThread][E][internal_api][backupdaemon.py:write_job_failed_event_log:133] : [Hybrid Backup Sync] Failed to complete Backup job: "backup-versity". Download diagnostic report and contact QNAP support. Error: ValueError
```

Looks like it doesn't enjoy the received time string from versity now.

_Originally posted by @derreisende77 in https://github.com/versity/versitygw/issues/738#issuecomment-2304111197_

**Comment by benmcclelland** [comment]
@derreisende77 Do you have the gateway logs at the time this happens? I'm not sure which s3 api call its having trouble with.

**Comment by benmcclelland** [comment]
I think this might be within ListObjects and ListObjectsV2. This is a similar issue to the multipart error where the XML serialization isn't formatted the response correctly automatically.  I'll verify Listing response over here and see if we can get a fix together for this.

**Comment by derreisende77** [comment]
I made a new attempt and attach the output both from versity and the HBS backup log
[versity.log](https://github.com/user-attachments/files/16724861/versity.log)
[backupengine.log](https://github.com/user-attachments/files/16724866/backupengine.log)

**Comment by derreisende77** [comment]
I used versity with latest commit 8f89d32121c7cc83559ea60c0565b226dad518e0

**Comment by derreisende77** [comment]
FYI with the changes I am able to backup to versity again :) 300GB transferred and no problems. Thanks!
